baseURL = 'https://provagon.ru/'
languageCode = 'ru-ru'
title = 'VAGONAI'
enableRobotsTXT = true

[pagination]
  pagerSize = 10

[markup]
  [markup.goldmark]
    [markup.goldmark.renderer]
      unsafe = true
    [markup.goldmark.extensions]
      table = true
      strikethrough = true
      linkify = true
      taskList = true
