// Single source of truth for catalog content.
// Edit this file to update titles, descriptions, specs, images and prices.

window.PROVAGON_STATUS_LABELS = {
  in_stock: "В наличии",
  on_order: "Под заказ",
  after_repair: "После ремонта",
  new: "Новый",
};

window.PROVAGON_STATUS_COLORS = {
  in_stock: "#4ade80",
  on_order: "#facc15",
  after_repair: "#60a5fa",
  new: "#34d399",
};

window.PROVAGON_CATALOG = [
  {
    id: "gondola",
    title: "Полувагоны",
    subtitle: "Универсальная грузовая единица",
    intro:
      "Полувагоны — основа угольной и металлургической логистики. Высокая грузоподъёмность, открытый кузов для навалочных и штучных грузов.",
    image: "images/wagons/poluvagon.png",
    accentColor: "#5eead4",
    wagons: [
      {
        id: "gv-12-963",
        model: "12-963",
        description:
          "Полувагон 4-осный с люками в полу, с разгрузочными люками и глухими торцевыми стенами.",
        purpose: "Уголь, руда, лесоматериалы, строительные грузы",
        image: "images/wagons/12-963x1.png",
        specs: [
          { label: "Грузоподъёмность", value: "71 т" },
          { label: "Объём кузова", value: "87 м³" },
          { label: "Длина по осям", value: "13 920 мм" },
          { label: "База", value: "8 650 мм" },
          { label: "Осность", value: "4" },
          { label: "Скорость", value: "120 км/ч" },
          { label: "Тара (min/max)", value: "22,0 / 23,0 т" },
        ],
        status: "in_stock",
        price: "от 4 600 000 ₽",
        categoryId: "gondola",
      },
      {
        id: "gv-12-955",
        model: "12-955",
        description:
          "Цельнометаллический полувагон с глухим кузовом, предназначен для перевозки грузов, требующих защиты от атмосферных воздействий.",
        purpose: "Уголь, руда, торф, лесоматериалы",
        image: "images/wagons/12-955x1.png",
        specs: [
          { label: "Грузоподъёмность", value: "71 т" },
          { label: "Объём кузова", value: "88 м³" },
          { label: "Длина по осям", value: "13 920 мм" },
          { label: "База", value: "8 650 мм" },
          { label: "Осность", value: "4" },
          { label: "Скорость", value: "120 км/ч" },
          { label: "Тара", value: "23 т" },
        ],
        status: "in_stock",
        price: "от 4 500 000 ₽",
        categoryId: "gondola",
      },
      {
        id: "gv-12-9046",
        model: "12-9046",
        description:
          "Полувагон цельнометаллический с глухими торцевыми стенками и разгрузочными люками для эффективной выгрузки.",
        purpose: "Уголь, руда, кокс, строительные материалы",
        image: "images/wagons/12-9046x1.png",
        specs: [
          { label: "Грузоподъёмность", value: "70 т" },
          { label: "Объём кузова", value: "85 м³" },
          { label: "Длина по осям", value: "13 920 мм" },
          { label: "База", value: "8 650 мм" },
          { label: "Осность", value: "4" },
          { label: "Скорость", value: "120 км/ч" },
          { label: "Тара", value: "24 т" },
        ],
        status: "in_stock",
        price: "от 4 550 000 ₽",
        categoryId: "gondola",
      },
    ],
  },
  {
    id: "hopper",
    title: "Хопперы",
    subtitle: "Быстрая разгрузка, высокая производительность",
    intro:
      "Хопперы-зерновозы, минераловозы и цементовозы. Конический бункер обеспечивает самотёчную выгрузку без дополнительного оборудования.",
    image: "images/wagons/hopper.png",
    accentColor: "#93c5fd",
    wagons: [
      {
        id: "hp-19-923",
        model: "19-923 (19-923-02)",
        description:
          "Вагон-хоппер для минеральных удобрений с увеличенным объемом кузова.",
        purpose: "Минеральные удобрения",
        image: "images/wagons/19-923(19-923-02)x1.png",
        specs: [
          { label: "Грузоподъёмность", value: "70 т" },
          { label: "Объём кузова", value: "81 м³" },
          { label: "Длина по осям", value: "13 200 мм" },
          { label: "База", value: "8 980 мм" },
          { label: "Высота", value: "4 914 мм" },
          { label: "Скорость", value: "120 км/ч" },
          { label: "Тара", value: "23 т" },
        ],
        status: "on_order",
        price: "от 5 500 000 ₽",
        categoryId: "hopper",
      },
      {
        id: "hp-19-923a",
        model: "19-923A",
        description:
          "Вагон-хоппер для сыпучих стройматериалов, таких как щебень, гравий, песок.",
        purpose: "Сыпучие стройматериалы (щебень, гравий, песок)",
        image: "images/wagons/19-923Ax1.png",
        specs: [
          { label: "Грузоподъёмность", value: "70 т" },
          { label: "Объём кузова", value: "61 м³" },
          { label: "Длина по осям", value: "13 200 мм" },
          { label: "База", value: "8 980 мм" },
          { label: "Высота", value: "3 990 мм" },
          { label: "Скорость", value: "120 км/ч" },
          { label: "Тара", value: "22 т" },
        ],
        status: "in_stock",
        price: "от 5 350 000 ₽",
        categoryId: "hopper",
      },
      {
        id: "hp-19-953",
        model: "19-953 (19-953-02)",
        description:
          "Вагон-хоппер для минеральных удобрений с увеличенным объемом кузова.",
        purpose: "Минеральные удобрения",
        image: "images/wagons/19-953(19-953-02)x1.png",
        specs: [
          { label: "Грузоподъёмность", value: "70 т" },
          { label: "Объём кузова", value: "89 м³" },
          { label: "Длина по осям", value: "13 200 мм" },
          { label: "База", value: "8 980 мм" },
          { label: "Высота", value: "5 120 мм" },
          { label: "Скорость", value: "120 км/ч" },
          { label: "Тара", value: "24 т" },
        ],
        status: "in_stock",
        price: "от 5 600 000 ₽",
        categoryId: "hopper",
      },
      {
        id: "hp-19-953-01",
        model: "19-953-01 (19-953-03)",
        description:
          "Вагон-хоппер для минеральных удобрений с выгрузкой в межрельсовое пространство.",
        purpose: "Минеральные удобрения",
        image: "images/wagons/19-953-01(19-953-03)x1.png",
        specs: [
          { label: "Грузоподъёмность", value: "70 т" },
          { label: "Объём кузова", value: "89 м³" },
          { label: "Длина по осям", value: "13 200 мм" },
          { label: "База", value: "8 980 мм" },
          { label: "Высота", value: "5 120 мм" },
          { label: "Скорость", value: "120 км/ч" },
          { label: "Тара", value: "24 т" },
        ],
        status: "in_stock",
        price: "от 5 400 000 ₽",
        categoryId: "hopper",
      },
      {
        id: "hp-19-969",
        model: "19-969",
        description: "Вагон-хоппер для цемента с гравитационной разгрузкой.",
        purpose: "Цемент",
        image: "images/wagons/19-969x1.png",
        specs: [
          { label: "Грузоподъёмность", value: "73 т" },
          { label: "Объём кузова", value: "65 м³" },
          { label: "Длина по осям", value: "12 020 мм" },
          { label: "База", value: "7 800 мм" },
          { label: "Высота", value: "4 400 мм" },
          { label: "Скорость", value: "120 км/ч" },
          { label: "Тара", value: "21 т" },
        ],
        status: "in_stock",
        price: "от 4 900 000 ₽",
        categoryId: "hopper",
      },
      {
        id: "hp-19-970-01",
        model: "19-970-01",
        description:
          "Вагон-хоппер для зерна с большим объемом кузова и гравитационной разгрузкой.",
        purpose: "Зерно, зернобобовые культуры",
        image: "images/wagons/19-970-01x1.png",
        specs: [
          { label: "Грузоподъёмность", value: "70,5 т" },
          { label: "Объём кузова", value: "110 м³" },
          { label: "Длина по осям", value: "14 720 мм" },
          { label: "База", value: "10 500 мм" },
          { label: "Высота", value: "5 000 мм" },
          { label: "Скорость", value: "120 км/ч" },
          { label: "Тара", value: "23,5 т" },
        ],
        status: "on_order",
        price: "от 8 400 000 ₽",
        categoryId: "hopper",
      },
    ],
  },
  {
    id: "tanker",
    title: "Цистерны",
    subtitle: "Жидкие грузы любой категории",
    intro:
      "Нефтебензиновые, кислотные, пищевые цистерны. Сертифицированы для перевозки опасных грузов 3–6 класса. Специальные покрытия под заказ.",
    image: "images/wagons/cisterna.png",
    accentColor: "#fbbf24",
    wagons: [
      {
        id: "tn-17-932",
        model: "17-932",
        description:
          "Вагон-цистерна для транспортировки цемента с пневматической системой разгрузки.",
        purpose: "Цемент",
        image: "images/wagons/17-932x1.png",
        specs: [
          { label: "Грузоподъёмность", value: "64 т" },
          { label: "Длина по осям", value: "14 120 мм" },
          { label: "База", value: "9 900 мм" },
          { label: "Объём", value: "3 емкости" },
          { label: "Скорость", value: "120 км/ч" },
          { label: "Тара", value: "30 т" },
        ],
        status: "on_order",
        price: "По запросу",
        categoryId: "tanker",
      },
      {
        id: "tn-17-917-01",
        model: "17-917-01",
        description:
          "Вагон-цистерна для перевозки аммиачной селитры с гравитационной разгрузкой.",
        purpose: "Аммиачная селитра",
        image: "images/wagons/17-917-01x1.png",
        specs: [
          { label: "Грузоподъёмность", value: "58 т" },
          { label: "Объём кузова", value: "80 м³" },
          { label: "Длина по осям", value: "17 480 мм" },
          { label: "База", value: "13 350 мм" },
          { label: "Скорость", value: "120 км/ч" },
          { label: "Тара", value: "36 т" },
        ],
        status: "on_order",
        price: "По запросу",
        categoryId: "tanker",
      },
    ],
  },
  {
    id: "covered",
    title: "Крытые вагоны",
    subtitle: "Защита груза от атмосферных воздействий",
    intro:
      "Универсальные крытые вагоны для штучных, тарных и пакетированных грузов. Укреплённые стены, двери с запором, вентиляционные решётки.",
    image: "images/wagons/kritie.png",
    accentColor: "#a78bfa",
    wagons: [
      {
        id: "cv-13-975",
        model: "13-975",
        description:
          "Крытый вагон-платформа, специализированный для перевозки стали в рулонах.",
        purpose: "Сталь в рулонах",
        image: "images/wagons/13-975x1.png",
        specs: [
          { label: "Грузоподъёмность", value: "70 т" },
          { label: "Длина по осям", value: "11 920 мм" },
          { label: "База", value: "3 240 мм" },
          { label: "Осность", value: "4" },
          { label: "Тара", value: "24 т" },
          { label: "Скорость", value: "120 км/ч" },
        ],
        status: "on_order",
        price: "По запросу",
        categoryId: "covered",
      },
      {
        id: "cv-11-965",
        model: "11-965",
        description:
          "Крытый вагон с раздвижным кузовом для перевозки крупногабаритных и длинномерных грузов, требующих защиты от непогоды.",
        purpose: "Пиломатериалы, металлопрокат, оборудование",
        image: "images/wagons/11-965x1.png",
        specs: [
          { label: "Грузоподъёмность", value: "62 т" },
          { label: "Объём кузова", value: "190 м³" },
          { label: "Длина по осям", value: "19 620 мм" },
          { label: "База", value: "14 400 мм" },
          { label: "Осность", value: "4" },
          { label: "Скорость", value: "120 км/ч" },
        ],
        status: "on_order",
        price: "По запросу",
        categoryId: "covered",
      },
    ],
  },
  {
    id: "flatcar",
    title: "Платформы",
    subtitle: "Тяжеловесные и негабаритные грузы",
    intro:
      "Универсальные, контейнерные, лесовозные и транспортёрные платформы. Специальные сцепки для сверхдлинных и сверхтяжёлых грузов.",
    image: "images/wagons/platforma.png",
    accentColor: "#f97316",
    wagons: [
      {
        id: "pl-13-935a",
        model: "13-935А",
        description:
          "Платформа для перевозки крупнотоннажных контейнеров, оснащенная упорами для надежного крепления.",
        purpose: "20-, 40-футовые контейнеры ISO",
        image: "images/wagons/13-935Аx1.jpg",
        specs: [
          { label: "Грузоподъёмность", value: "71 т" },
          { label: "Длина по осям", value: "19 620 мм" },
          { label: "База", value: "14 400 мм" },
          { label: "Осность", value: "4" },
          { label: "Тара", value: "23 т" },
          { label: "Упоры", value: "16 шт" },
        ],
        status: "in_stock",
        price: "от 4 500 000 ₽",
        categoryId: "flatcar",
      },
      {
        id: "pl-13-935a-01",
        model: "13-935А-01",
        description:
          "Унифицированная платформа с увеличенным количеством упоров для перевозки крупнотоннажных контейнеров.",
        purpose: "20-, 40-, 45-футовые контейнеры ISO",
        image: "images/wagons/13-935А-01x1.png",
        specs: [
          { label: "Грузоподъёмность", value: "71 т" },
          { label: "Длина по осям", value: "19 620 мм" },
          { label: "База", value: "14 400 мм" },
          { label: "Осность", value: "4" },
          { label: "Тара", value: "23 т" },
          { label: "Упоры", value: "24 шт" },
        ],
        status: "in_stock",
        price: "от 5 500 000 ₽",
        categoryId: "flatcar",
      },
      {
        id: "pl-13-935a-03",
        model: "13-935А-03",
        description:
          "Платформа для перевозки крупнотоннажных контейнеров, адаптированная для различных типов грузов.",
        purpose: "20-, 40-футовые контейнеры ISO",
        image: "images/wagons/13-935А-03x1.png",
        specs: [
          { label: "Грузоподъёмность", value: "69 т" },
          { label: "Длина по осям", value: "19 620 мм" },
          { label: "База", value: "14 400 мм" },
          { label: "Осность", value: "4" },
          { label: "Тара", value: "25 т" },
          { label: "Упоры", value: "16 шт" },
        ],
        status: "in_stock",
        price: "от 4 700 000 ₽",
        categoryId: "flatcar",
      },
      {
        id: "pl-23-925",
        model: "23-925",
        description:
          "Унифицированная платформа для перевозки лесоматериалов и хлыстов.",
        purpose: "Лесоматериалы, хлысты, трубы",
        image: "images/wagons/23-925x1.png",
        specs: [
          { label: "Грузоподъёмность", value: "60 т" },
          { label: "Объём кузова", value: "165 м³" },
          { label: "Длина по осям", value: "23 220 мм" },
          { label: "База", value: "17 750 мм" },
          { label: "Осность", value: "4" },
          { label: "Скорость", value: "120 км/ч" },
        ],
        status: "in_stock",
        price: "от 4 500 000 ₽",
        categoryId: "flatcar",
      },
      {
        id: "pl-13-192-01",
        model: "13-192-01",
        description:
          "Универсальная платформа для перевозки широкой номенклатуры грузов, включая контейнеры и колесную технику.",
        purpose: "Контейнеры, техника, металлопрокат",
        image: "images/wagons/13-192-01x1.png",
        specs: [
          { label: "Грузоподъёмность", value: "45 т" },
          { label: "Длина по осям", value: "14 620 мм" },
          { label: "База", value: "13 400 мм" },
          { label: "Осность", value: "4" },
          { label: "Тара", value: "21,5 т" },
        ],
        status: "on_order",
        price: "По запросу",
        categoryId: "flatcar",
      },
    ],
  },
  {
    id: "dumpcar",
    title: "Думпкары",
    subtitle: "Карьерная и горная логистика",
    intro:
      "Вагоны-самосвалы для горнодобывающей отрасли. Гидравлический или пневматический привод опрокидывания. Работают в условиях Крайнего Севера.",
    image: "images/wagons/dumpkar.png",
    accentColor: "#fb7185",
    wagons: [
      {
        id: "dc-34-9023",
        model: "34-9023",
        description:
          "Мощный вагон-самосвал для перевозки и выгрузки горной массы, руды и вскрышных пород.",
        purpose: "Руда, порода, уголь",
        image: "images/wagons/34-9023x1.png",
        specs: [
          { label: "Грузоподъёмность", value: "150 т" },
          { label: "Объём кузова", value: "60 м³" },
          { label: "Длина по осям", value: "18 400 мм" },
          { label: "База", value: "10 400 мм" },
          { label: "Осность", value: "8" },
          { label: "Привод", value: "Пневматический" },
        ],
        status: "on_order",
        price: "По запросу",
        categoryId: "dumpcar",
      },
      {
        id: "dc-31-945",
        model: "31-945",
        description:
          "Вагон-самосвал (думпкар) для перевозки сыпучих грузов в карьерах и на строительных объектах.",
        purpose: "Руда, уголь, порода, песок, щебень",
        image: "images/wagons/31-945x1.png",
        specs: [
          { label: "Грузоподъёмность", value: "66 т" },
          { label: "Объём кузова", value: "36 м³" },
          { label: "Длина по осям", value: "11 830 мм" },
          { label: "База", value: "7 500 мм" },
          { label: "Осность", value: "4" },
          { label: "Привод", value: "Пневматический" },
        ],
        status: "in_stock",
        price: "от 9 800 000 ₽",
        categoryId: "dumpcar",
      },
      {
        id: "dc-33-9035",
        model: "33-9035",
        description:
          "Вагон-самосвал повышенной грузоподъемности для тяжелых условий эксплуатации в горнорудной промышленности.",
        purpose: "Руда, порода, уголь",
        image: "images/wagons/33-9035x1.png",
        specs: [
          { label: "Грузоподъёмность", value: "105 т" },
          { label: "Объём кузова", value: "50 м³" },
          { label: "Длина по осям", value: "15 036 мм" },
          { label: "База", value: "9 340 мм" },
          { label: "Осность", value: "8" },
          { label: "Привод", value: "Пневматический" },
        ],
        status: "in_stock",
        price: "от 18 100 000 ₽",
        categoryId: "dumpcar",
      },
    ],
  },
  {
    id: "transporter",
    title: "Транспортеры",
    subtitle: "Для негабаритных и сверхтяжелых грузов",
    intro:
      "Железнодорожные транспортеры различных типов для перевозки тяжеловесных и крупногабаритных грузов, которые невозможно перевезти на обычных платформах.",
    image: "images/wagons/transporter.png",
    accentColor: "#f59e0b",
    wagons: [
      {
        id: "tr-14-9037",
        model: "14-9037",
        description:
          "Транспортер для перевозки транспортных упаковочных комплектов типа ТУК-13 (например, для отработавшего ядерного топлива).",
        purpose: "Специальные упаковочные комплекты",
        image: "images/wagons/14-9037x1.png",
        specs: [
          { label: "Грузоподъёмность", value: "126 т" },
          { label: "Длина по осям", value: "25 300 мм" },
          { label: "База", value: "13 450 мм" },
          { label: "Осность", value: "12" },
          { label: "Тара", value: "84 т" },
          { label: "Скорость", value: "100 км/ч" },
        ],
        status: "on_order",
        price: "По запросу",
        categoryId: "transporter",
      },
      {
        id: "tr-14-6057",
        model: "14-6057",
        description:
          "Транспортер железнодорожный сочлененного типа, предназначенный для перевозки тяжелых грузов.",
        purpose: "Трансформаторы, реакторы, крупное оборудование",
        image: "images/wagons/14-6057x1.png",
        specs: [
          { label: "Грузоподъёмность", value: "240 т" },
          { label: "Длина по осям", value: "32 600 мм" },
          { label: "Осность", value: "16" },
          { label: "Тара", value: "112 т" },
          { label: "Скорость", value: "100 км/ч" },
        ],
        status: "on_order",
        price: "По запросу",
        categoryId: "transporter",
      },
      {
        id: "tr-14-9038",
        model: "14-9038",
        description:
          "Транспортер сочлененного типа для перевозки тяжеловесных и крупногабаритных грузов.",
        purpose: "Крупногабаритное оборудование",
        image: "images/wagons/14-9038x1.png",
        specs: [
          { label: "Грузоподъёмность", value: "170 т" },
          { label: "Осность", value: "16" },
          { label: "Тара", value: "92 т" },
          { label: "Скорость (порожний)", value: "120 км/ч" },
        ],
        status: "on_order",
        price: "По запросу",
        categoryId: "transporter",
      },
    ],
  },
  {
    id: "parts",
    title: "Запасные части",
    subtitle: "Комплектующие и сервис",
    intro:
      "Тележки ЦНИИ-Х3, колёсные пары, автосцепки, тормозные системы. Оригинальные и сертифицированные аналоги для всех типов вагонов.",
    image: "images/wagons/zapchasti.png",
    accentColor: "#86efac",
    wagons: [
      {
        id: "pts-18-100",
        model: "18-100",
        description:
          "Двухосная тележка грузовых вагонов (модель ЦНИИ-Х3) — основная модель для типового подвижного состава.",
        purpose: "Для полувагонов, крытых вагонов, платформ, хопперов",
        image: "images/wagons/18-100x1.png",
        specs: [
          { label: "База", value: "1 850 мм" },
          { label: "Конструкционная скорость", value: "120 км/ч" },
          { label: "Нагрузка от оси на рельсы", value: "230 кН (23,5 тс)" },
          { label: "Тип рессорного подвешивания", value: "центральное" },
        ],
        status: "in_stock",
        price: "от 680 000 ₽",
        categoryId: "parts",
      },
      {
        id: "pts-18-999",
        model: "18-999",
        description:
          "Двухосная тележка с улучшенными характеристиками для грузовых вагонов.",
        purpose: "Для современных грузовых вагонов",
        image: "images/wagons/18-999x1.png",
        specs: [
          { label: "База", value: "1 850 мм" },
          { label: "Конструкционная скорость", value: "120 км/ч" },
          { label: "Нагрузка от оси на рельсы", value: "230 кН (23,5 тс)" },
          { label: "Гибкость подвешивания", value: "11,3 мм/тс" },
        ],
        status: "on_order",
        price: "от 750 000 ₽",
        categoryId: "parts",
      },
      {
        id: "kp-ru1sh",
        model: "РУ1Ш-950А",
        description: "Колесная пара с буксовыми узлами для грузовых вагонов.",
        purpose: "Для тележек грузовых вагонов",
        image: "images/wagons/РУ1Ш-950Аx1.png",
        specs: [
          { label: "Масса", value: "1 392 кг" },
          { label: "Диаметр колес по кругу катания", value: "957 мм" },
          { label: "Тип подшипников", value: "30-232726Л4М, 30-42726Л4М" },
          { label: "Нагрузка от оси", value: "230 кН (23,5 тс)" },
        ],
        status: "in_stock",
        price: "По запросу",
        categoryId: "parts",
      },
    ],
  },
];

window.PROVAGON_AI_SUGGESTIONS = [
  "Нужен хоппер-зерновоз под 10 000 тонн в месяц",
  "Сравни платформы 13-935А и 13-935А-03",
  "Полувагон б/у в наличии до 3 млн рублей",
  "Что выбрать для перевозки контейнеров?",
  "Есть ли в наличии думпкары 33-9035?",
  "Нужна тележка 18-100 для ремонта",
];
